include(FetchContent)

include(LoadSpdlog)
include(LoadDataManagement)
include(LoadSQLiteCpp)
if(HEPCE_BUILD_TESTS STREQUAL "OFF")
    FetchContent_MakeAvailable(SQLiteCpp spdlog datamanagement)
elseif(HEPCE_BUILD_TESTS STREQUAL "ON")
    include(LoadGtest)
    FetchContent_MakeAvailable(SQLiteCpp spdlog googletest datamanagement)
    include(GoogleTest)
endif()
