name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Build Release
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    # Load the conda environment
    - name: Load Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml
        auto-activate-base: false
        activate-environment: hepce

    - name: Check Conda Environment
      run: |
        conda info
        # ensure the packages are installed in the env
        conda env export

    - name: Clone and Build DataManagement
      working-directory: ${{ github.workspace }}
      run: |
        gh repo clone SyndemicsLab/DataManagement
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      working-directory: ${{ github.workspace }}
      run: scripts/build.sh -p

    - name: Cmake test
      working-directory: ${{ github.workspace }}/bin
      run: ./hepceTest
