name: Release Project

on:
    push:
        tags:
            - "v*.*.*"

env:
    BUILD_TYPE: Release

jobs:
    build-and-release:
        name: Build Release
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v4
            - name: Install SQLiteCpp
              run: sudo apt-get install libsqlitecpp-dev
            - name: Build and Test
              working-directory: ${{ github.workspace }}
              run: cmake --workflow --preset gcc-release

            - name: Create Release
              id: create_release
              uses: actions/create-release@latest
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
