name: HEP-CE Unit Tests
# Schema: https://json.schemastore.org/github-action.json

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unit-testing:
        name: Testing ${{ matrix.os }} ${{matrix.build-variant}} build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # macos-latest
                build-variant: [shared, static]
        steps:
            - name: Checkout HEP-CE
              uses: actions/checkout@v6

            - name: Install Windows Dependencies
              if: matrix.os == 'windows-latest'
              uses: msys2/setup-msys2@v2
              with:
                  msystem: UCRT64
                  update: true
                  install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-sqlite3

            - name: Install Boost In Linux
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install -y libboost-dev

            - name: Run Testing Workflow
              run: cmake --workflow --preset debug-${{matrix.build-variant}}
              timeout-minutes: 10
              shell: bash
